"""
Safe rebuild of the vector store after the embedding-model swap.

Because embeddings are now generated by `gemini-embedding-001` instead of
the old local TF-IDF+SVD vectors, any existing ./chroma_db collection from
before this upgrade must NOT be reused -- mixing vectors from two different
embedding models in one collection silently corrupts similarity search.

This script:
  1. Deletes any existing "properties" collection in ./chroma_db.
  2. Loads the knowledge-base documents (rag_pipeline.load_documents).
  3. Chunks them (unchanged 800-char/120-overlap default).
  4. Embeds each chunk with gemini-embedding-001 and stores it in a fresh
     ChromaDB collection.
  5. Reports how many documents/chunks were indexed.

Requires GOOGLE_API_KEY in .env. Run this once after setup, and again any
time the knowledge-base CSVs change.

    python rebuild_vectorstore.py
"""
from rag_pipeline import load_documents, build_chunks, get_vectorstore, index_chunks, CHROMA_DIR, COLLECTION_NAME


def main():
    print(f"Rebuilding vector store at {CHROMA_DIR} (collection: {COLLECTION_NAME})")
    print("Embedding model: gemini-embedding-001 (see config.GEMINI_EMBEDDING_MODEL)")

    vectorstore = get_vectorstore()
    try:
        vectorstore.delete_collection()
        print("Deleted existing collection (old embeddings, if any).")
        vectorstore = get_vectorstore()  # recreate empty
    except Exception as e:
        print(f"No existing collection to delete ({e}) -- starting fresh.")

    docs = load_documents()
    print(f"Loaded {len(docs)} source documents (locality profiles, payment plans, FAQs).")

    chunks = build_chunks(docs, chunk_size=800, overlap=120)
    print(f"Built {len(chunks)} chunks.")

    n = index_chunks(vectorstore, chunks)
    print(f"Indexed {n} chunks into ChromaDB using gemini-embedding-001.")
    print("Done. Vector store persisted at", CHROMA_DIR)


if __name__ == "__main__":
    main()
